trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: InstallTerraform
  displayName: 'Install and initialize Terraform'
  steps:
  - script: |
      if [ ! -f /usr/local/bin/terraform ]; then
          wget https://releases.hashicorp.com/terraform/0.14.11/terraform_0.14.11_linux_amd64.zip
          unzip terraform_0.14.11_linux_arm64.zip -d terraform_temp
          chmod +x terraform_temp/terraform
          mv terraform_temp/terraform /usr/local/bin/
      else
          mv /usr/local/bin/terraform /usr/local/bin/terraform.old
          wget https://releases.hashicorp.com/terraform/0.14.11/terraform_0.14.11_linux_arm64.zip
          unzip terraform_0.14.11_linux_arm64.zip -d terraform_temp
          chmod +x terraform_temp/terraform
          mv terraform_temp/terraform /usr/local/bin/
      fi
    displayName: 'Install and initialize Terraform'

- job: InstallAndScan
  displayName: 'Install and Scan'
  steps:
  - script: |
      # Install the tool
      wget https://artifacts.rapid7.com/cloudsec/mimics/v1.2.5/mimics_1.2.5_linux_amd64 -O $(Agent.ToolsDirectory)/mimics
      chmod +x $(Agent.ToolsDirectory)/mimics
    displayName: 'Install mimics-binary'

  - script: |
      # Use the installed tool for scanning
      $(Agent.ToolsDirectory)/mimics scan $(System.DefaultWorkingDirectory) --api-key $(API_KEY) --base-url $(BASE_URL) --no-verify --ics-config "ICS Demo NIST PRD Fail" --log-format json --report-formats all --report-name results-rapid7_iac --no-fail --verbose
    displayName: 'Scan IaC files with Mimics'

  - script: |
      # Move the HTML, SARIF and XML reports to a designated directory
      mkdir -p $(System.DefaultWorkingDirectory)/mimics-reports
      mv $(System.DefaultWorkingDirectory)/*.html $(System.DefaultWorkingDirectory)/*.xml $(System.DefaultWorkingDirectory)/*.sarif $(System.DefaultWorkingDirectory)/mimics-reports/
    displayName: 'Move HTML, SARIF and XML Reports'

  # Publish additional files (results-rapid7_iac artifacts)
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Scan Artifacts'
    inputs:
      pathtoPublish: '$(System.DefaultWorkingDirectory)/mimics-reports'
      artifactName: 'results-rapid7_iac2'

  # Publish the HTML report using the PublishHtmlReport task
  - task: PublishHtmlReport@1
    condition: succeededOrFailed()
    inputs:
      reportDir: $(System.DefaultWorkingDirectory)/mimics-reports/results-rapid7_iac.html
      tabName: 'R7 IaC Code'
      
